### ISSUE TITLE
The extends tag interferes with the simple-menu template tags

### ISSUE THREAD

**Issue by gtoffoli** [fatbox/django-simple-menu#33]
Hi,
I had used simple-menu with satisfaction a couple of years ago. In a new project, it appeared not to work anymore.
After tweaking a few hours, I realized that the only difference in my code was the use of the **extends** tag in the template.
If your template extends another one, you have to move to the latter the tags *{% load menu %}* and *{% generate_menu %}*; otherways, the **menus** context variable is not defined.
But I think that not having to modify directly a generic template is just why *extends* exist.
Anyway, many thanks to the creator of the django-simple-menu app! Really it allows to create "Simple, yet powerful, code-based menus for Django applications".

**Comment by borgstrom** [comment]
Thanks for the report.  Could you provide a gist showing a template that exhibits this problem?  It will be easier for me to fix if I have a concrete example.

**Comment by gtoffoli** [comment]
Thank you, Evan, for your reply.

I already had a python virtualenv with:
- python 2.7
- django 1.6.8 (I still have to upgrade)
- django-simple-menu django_simple_menu-1.0.9-py2.7

From https://github.com/fatbox/django-simple-menu downloaded latest commit e3a5e04464 and copied the entire example subfolder in my *virtualenv*.
Then executed `syncdb` and `runserver`.

1. At first access, got the homepage with the expected menus:
>User Menu
>    Login
>Main Menu
>    Accounts Index
>    Reports Index
>Accounts Index 

2. Then, in the **base.html** template of the *accounts* app, added the following code just after the `<body>` tag:
`<div>{{ menus }}</div>`
and got the same screen as above, with this line added at the top: 
`{'main': [<menu.menu.MenuItem object at 0x02F28590>, <menu.menu.MenuItem object at 0x02F82730>], 'user': [<menu.menu.MenuItem object at 0x02F82110>]}`

3. Finally, created a **zero.htm** template containing only the following code
>  {% block all %}
>  {% endblock %}
further modified the **base.html** template as shown below, and got screen with only this text:
>User Menu
>Main Menu
>Accounts Index 

---------------------------  **base.html** in step 3.
`{% extends "zero.html" %}`
`{% load menu %}{% generate_menu %}`
`{% block all %}`
`	<html>`
`	    <head>`
`	        <title>{% block title %}No title set{% endblock %}</title>`
`	        {% block headextra %}{% endblock %}`
`	    </head>`
`	    <body>`
`	<div>{{ menus }}</div>`
`	...`
`	    </body>`
`	</html>`
`{% endblock %}`

**Comment by borgstrom** [comment]
Hi @gtoffoli,

The issue here is actually with your base.html, and the fact that `{% generate_menu %}` never gets evaluated because it is outside of a block in a child template.  When a template uses the `{% extends "file" %}` directive the template engine then only looks at blocks in that files that are present in the parent template.

If you change your base.html to read:

```
{% extends "zero.html" %}
{% load menu %}

{% block all %}
{% generate_menu %}
...
```

Then it works as expected.
